### ISSUE TITLE
Error installing requirements.txt

### ISSUE THREAD

**Issue by aleczazam** [dragonked2/Egy-Crack#7]
Ok so I am trying to get the requirements.txt to install but it gets errors so I installed them individually but I still get errors trying to install coincurve==15.0.0 

When I run on pydroid terminal I get this error

**Comment by aleczazam** [comment]
Installed all requirements and then got this error when running python crack.py

/storage/emulated/0/Android/data/ru.iiec.pydroid3/Egy $ python Crack.py
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/ru.iiec.pydroid3/Egy/Crack.py", line 1, in <module>
    from eth_account import Account
ModuleNotFoundError: No module named 'eth_account'
/storage/emulated/0/Android/data/ru.iiec.pydroid3/Egy $ /storage/emulated/0/Android/data/ru.iiec.pydroid3/Egy $

**Comment by aleczazam** [comment]
Got it down to 1 error 

Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/ru.iiec.pydroid3/Egy/crack.py", line 1, in <module>
    from eth_account import Account
ModuleNotFoundError: No module named 'eth_account'
/storage/emulated/0/Android/data/ru.iiec.pydroid3/Egy $

**Comment by aleczazam** [comment]
So I'm guessing I need to change eth_as accounts to something else? Can anyone lend a hand?
